# WebRTC-MCU
# git https://github.com/xivistudios/webrtc-mcu
# Copyright(c) 2018-2023 Mr.Panda xivistudios
# MIT Licensed

# http配置
[http]
host = "www.xivistudios.com"
port = 80
ssl = true
key = "DSAIOsjopKJnkaKPKpkkGYUGkkHUIa=="

# api配置
[api]
http = "/api"
websocket = "/masterApi"

# mongodb
[mongodb]
host = "127.0.0.1"
port = 27017
dbname = "nuvedb"
document = [
  "key",
  "keys",
  "rooms",
  "services",
  "tokens"
]