[nuve]
keystorePath = "./cert/certificate.pfx"
superserviceID = "5af67653f7ea137358023ec6"
ssl = false #default: false
port = 3000 #default: 3000, port of nuve server
numberOfProcess = 4 #default: 1

[cluster]
name = "woogeen-cluster"

[rabbit]
host = "localhost" #default: "localhost"
port = 5672 #default: 5672

[mongo]
dataBaseURL = "localhost/nuvedb" #default: "localhost/nuvedb"

# websocket配置
[websocket]
host = "ws://localhost/masterApi"