# WebRTC-MCU
# git https://github.com/xivistudios/webrtc-mcu
# Copyright(c) 2018-2023 Mr.Panda xivistudios
# MIT Licensed

# http配置
[http]
host = "localhost"
port = 80
origin = "http://localhost"
views = "E://Package/webrtc-mcu/page/html"
public = "E://Package/webrtc-mcu/page/public"

# http session 配置
[session]
name = "TokenSession"
maxAge = 604800000
keys = [
  "dskaopd8sa908csacu89u9c", 
  "cad8c90a8c8as8cx8a8csac6tc7"
]

# mongodb数据库连接配置
[mongodb]
path = "mongodb://192.168.126.128:27017"
dbname = "intelmcu"
document = [
  "admin",
  "event",
  "log"
]

# mongodb数据库认证配置
[mongodb.auth]
user = "Adminstrators"
password = "xiaopange520"

# redis数据库连接配置
[redis]
host = "192.168.126.128"
port = 6379

# 加密配置
[crypto]
type = "aes256"
key = "csakopkdsoai08978c07c08"

# 邮件服务配置
[nodemailer]
service = "smtp.163.com"
host = "smtp.163.com"
port = 465
secureConnection = true
secure = true

# 邮件服务认证配置
[nodemailer.auth]
user = "duozan55@163.com"
pass = "duozhuan886688"