# WebRTC-MCU
# git https://github.com/xivistudios/webrtc-mcu
# Copyright(c) 2018-2023 Mr.Panda xivistudios
# MIT Licensed

# http配置
[http]
host = "localhost"
port = 80
origin = "http://localhost"
views = "E://Package/webrtc-mcu/page/html"
public = "E://Package/webrtc-mcu/page/public"

# http session 配置
[session]
name = "TokenSession"
maxAge = 604800000
keys = [
  "dskaopd8sa908csacu89u9c", 
  "cad8c90a8c8as8cx8a8csac6tc7"
]

# mongodb数据库连接配置
[mongodb]
host = "106.15.66.51"
port = 27017
dbname = "console"
document = [
  "admin",
  "log",
  "system",
  "cluster"
]

# mongodb数据库认证配置
[mongodb.auth]
user = "panda"
password = "xiaopange520"

# redis数据库连接配置
[redis]
host = "106.15.66.51"
port = 6379

# 加密配置
[crypto]
type = "aes256"
key = "csakopkdsoai08978c07c08"

# 邮件服务配置
[nodemailer]
service = "smtp.qq.com"
host = "smtp.qq.com"
port = 465
secureConnection = true
secure = true

# 邮件服务认证配置
[nodemailer.auth]
user = "1198100147@qq.con"
pass = "fxcmkcycmkzfhijb"

# 管理服务接入端口
[service]
port = 88
router = "/masterApi"

# 日志配置
[log]
path = "E://Package/webrtc-mcu/mcu.log"

# mcu服务id
[mcu]
superServiceId = "5af67653f7ea137358023ec6"
superServiceKey = "65sUUxO/VNbqmnyOy21vYDCZDDFwxsHOXCitou8xs5EqSJLbE0HQmwaVX5dM2psENArqknBU2erbFW4d7AH7UzQ2VO+jzbD2+GmXy2YWnZA6kz7tMpl+V9pCzI72fUyNZoQrLa0dOCi3HtaLTqnQo2t9FB5cjaLT3UVNdmXDTz8="
sampleServiceId = "5af67654f7ea137358023ec7"
sampleServiceKey = "kQI3boVIWe7cU7yRtK4GCsZbZ93afGQxmtRyH5CHH8EizhLs7eL83cnu1QL+FbLZYERaco2Z4TyXqT/ID0WE2txi6Ukc5CKOOWr16LXJzCmuvc5jAeIBwrBzWTprZG5CtQZ+tKm7IbAvVHaP1167Kl+SGfgAEl+8Rw5dUKsNzxo="
